WebApplication2/WebApplication2/Controllers/UrunlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models.Entity;

namespace WebApplication2.Controllers

{
    public class UrunlerController : Controller
    {
        // GET: Urunler
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLURUNLER.ToList();

            return View(degerler);
        }
        [HttpGet]
        public ActionResult newProduct()
        {
            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList()
                                                 //listeden öge seç --> select listItem
                                                 //TBLKATEGORI leriden verileri alıp i değişkenine atadık (LINQ)

                                             select new SelectListItem//yeni listeyi seç
                                             {
                                                 Text = i.KATEGORIAD,//seçmiş olduğun listenin text değeri= i den gelen kategoriAd
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            //text ile görünen kısma yazdırıyoruz value ile de arkaplanda döndürülen değer.

            //viewbag ifadesi controller kısmındaki ifadeyi diğer sayfaya (newProduct.cshtml) taşır.
            ViewBag.dgr = degerler;//dgr ismindeki viewbag değerler isimli listeyi başka bir sayfaya taşımamıza olanak sağlar.
            return View();

        }
        [HttpPost]
        public ActionResult newProduct(TBLURUNLER p1)
        {
            var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p1.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            Console.WriteLine(p1.TBLKATEGORILER.KATEGORIID);
            p1.TBLKATEGORILER = ktg;
            // "m" her bir TBLKATEGORILER kaydını temsil eden bir değişkendir
            db.TBLURUNLER.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        public ActionResult SIL(int id)
        {
            var urun = db.TBLURUNLER.Find(id);
            db.TBLURUNLER.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        public ActionResult UrunGetir(int id)
        {
            var urun = db.TBLURUNLER.Find(id);

            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList()
                                                 //listeden öge seç --> select listItem
                                                 //TBLKATEGORI leriden verileri alıp i değişkenine atadık (LINQ)

                                             select new SelectListItem//yeni listeyi seç
                                             {
                                                 Text = i.KATEGORIAD,//seçmiş olduğun listenin text değeri= i den gelen kategoriAd
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            //text ile görünen kısma yazdırıyoruz value ile de arkaplanda döndürülen değer.

            //viewbag ifadesi controller kısmındaki ifadeyi diğer sayfaya (newProduct.cshtml) taşır.
            ViewBag.dgr = degerler;//dgr ismindeki viewbag değerler isimli listeyi başka bir sayfaya taşımamıza olanak sağlar.
            return View("UrunGetir",urun);
        }

        public ActionResult Guncelle(TBLURUNLER p)
        {
            var urun = db.TBLURUNLER.Find(p.URUNID);
            urun.URUNAD = p.URUNAD;
            urun.MARKA = p.MARKA;
            urun.STOK = p.STOK;
            urun.FIYAT = p.FIYAT;

            var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            urun.URUNKATEGORI = ktg.KATEGORIID;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

WebApplication2/WebApplication2/Views/Urunler/Index.cshtml
@using WebApplication2.Models.Entity
@model List<TBLURUNLER>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>URUN ID</th>
        <th>URUN AD</th>
        <th>URUN KATEGORI</th>
        <th>FIYAT</th>
        <th>MARKA</th>
        <th>STOK</th>
        <th>SİL</th>
        <th>Güncelle</th>
    </tr>
    <tbody>
        @foreach (var urn in Model)
        {
            <tr>
                <td>@urn.URUNID</td>
                <td>@urn.URUNAD</td>
                <td>@(urn.TBLKATEGORILER != null ? urn.TBLKATEGORILER.KATEGORIAD : string.Empty)</td> <!--    Bu kısımda hata var!! TBLKATEGORILER:KATEGORIAD ı boş döndürüyor -->
                <td>@urn.FIYAT</td>
                <td>@urn.MARKA</td>
                <td>@urn.STOK</td>
                <td>
                    <a href="/URUNLER/SIL/@urn.URUNID" class="btn btn-danger">Delete</a>
                </td>
                <td>
                    <a href="/URUNLER/UrunGetir/@urn.URUNID" class="btn btn-success">Update</a>
                </td>
            </tr>
        }

    </tbody>
</table>
<a href="/URUNLER/newProduct" class="btn btn-primary">Add New Product</a>

WebApplication2/WebApplication2/Views/Urunler/UrunGetir.cshtml
@model WebApplication2.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<@using (Html.BeginForm("Guncelle", "Urunler", FormMethod.Post))
{

    <div class="form-group">
        @Html.LabelFor(m => m.URUNID)
        @Html.TextBoxFor(m => m.URUNID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.URUNAD)
        @Html.TextBoxFor(m => m.URUNAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.URUNKATEGORI)
        @Html.DropDownListFor(m=>m.TBLKATEGORILER.KATEGORIID,(List<SelectListItem>)ViewBag.dgr,new{ @class = "form-control" })
        @*@Html.TextBoxFor(m=>m.URUNKATEGORI,new{ @class="form-control})"*@       
 <br />
        @Html.LabelFor(m => m.FIYAT)
        @Html.TextBoxFor(m => m.FIYAT, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MARKA)
        @Html.TextBoxFor(m => m.MARKA, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.STOK)
        @Html.TextBoxFor(m => m.STOK, new { @class = "form-control" })



    </div>
    <div>
        <button class="btn btn-warning">Update Product</button>
    </div>

}

WebApplication2/WebApplication2/Views/Urunler/newProduct.cshtml
@model WebApplication2.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "newProduct";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>Product Name</label>
        <input type="text" name="URUNAD" class="form-control" required="" placeholder="Please enter product name" />
    </div>
    <div>
        <label>Product Category</label>
        @Html.DropDownListFor(m => m.TBLKATEGORILER.KATEGORIID, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
        <!-- m diye bir değer oluşturduk daha sonra m nin içine kategoriAd ı ata dedik, viewbag ile gelen değerlerli listeden çek dedik,

        ilk olarak html.dropdownlist ile combobox oluşturuyoruz.
        birinci parametre -> dropdownlistener de seçilen özelliği tblkategorıler.kategorııd ye bağlar.
        ikinci parametre -> DropDownList'da görünecek seçenekleri temsil eder.

        -->
    </div>
    <div>
        <label>Price</label>
        <input type="text" name="FIYAT" class="form-control" placeholder="Plese enter product price" />
    </div>
    <div>
        <label>Brand</label>
        <input type="text" name="MARKA" class="form-control" placeholder="Please enter product brand" />
    </div>
    <div>
        <label>Stock</label>
        <input type="text" name="STOK" class="form-control" placeholder="Please enter product stock" />
    </div>
    <div style="margin-top:15px">

        <button class="btn btn-info" id="btn3">Add Product</button>
    </div>
    <script>
        $('#btn3').click(function () {
            alert('Product Added Successfully');
        });
    </script>
</form>